var O=Object.create;var k=Object.defineProperty;var U=Object.getOwnPropertyDescriptor;var I=Object.getOwnPropertyNames;var W=Object.getPrototypeOf,R=Object.prototype.hasOwnProperty;var d=t=>k(t,"__esModule",{value:!0});var H=(t,e)=>()=>(e||t((e={exports:{}}).exports,e),e.exports),J=(t,e)=>{for(var n in e)k(t,n,{get:e[n],enumerable:!0})},Y=(t,e,n,a)=>{if(e&&typeof e=="object"||typeof e=="function")for(let r of I(e))!R.call(t,r)&&(n||r!=="default")&&k(t,r,{get:()=>e[r],enumerable:!(a=U(e,r))||a.enumerable});return t},L=(t,e)=>Y(d(k(t!=null?O(W(t)):{},"default",!e&&t&&t.__esModule?{get:()=>t.default,enumerable:!0}:{value:t,enumerable:!0})),t),j=(t=>(e,n)=>t&&t.get(e)||(n=Y(d({}),e,1),t&&t.set(e,n),n))(typeof WeakMap!="undefined"?new WeakMap:0);var T=H(p=>{p.version="0.1.0";var N=function(e){this.message=e,this.toString=function(){return this.constructor.name+": "+this.message}},y=function(e){this.firstWeekDay=e||0};y.prototype={constructor:y,weekStartDate:function(e){for(var n=new Date(e.getTime());n.getDay()!==this.firstWeekDay;)n.setDate(n.getDate()-1);return n},monthDates:function(e,n,a,r){if(typeof e!="number"||e<1970)throw new N("year must be a number >= 1970");if(typeof n!="number"||n<0||n>11)throw new N("month must be a number (Jan is 0)");var c=[],i=[],u=0,s=this.weekStartDate(new Date(e,n,1));do{for(u=0;u<7;u++)i.push(a?a(s):s),s=new Date(s.getTime()),s.setDate(s.getDate()+1);c.push(r?r(i):i),i=[]}while(s.getMonth()<=n&&s.getFullYear()===e);return c},monthDays:function(e,n){var a=function(c){return c.getMonth()===n?c.getDate():0};return this.monthDates(e,n,a)},monthText:function(e,n){if(typeof e=="undefined"){var a=new Date;e=a.getFullYear(),n=a.getMonth()}var r=function(u){for(var s=u.getMonth()===n?u.getDate().toString():"  ";s.length<2;)s=" "+s;return s},c=this.monthDates(e,n,r,function(i){return i.join(" ")});return c.join(`
`)}};var A="JAN FEB MAR APR MAY JUN JUL AUG SEP OCT NOV DEC".split(" ");for(w=0;w<A.length;w++)y[A[w]]=w;var w;p.Calendar=y});var G={};J(G,{default:()=>P});var o=require("@raycast/api"),l=require("react"),C=L(T());var z=6e4;var B=6048e5,V=(t,e)=>(t.getTimezoneOffset()-e.getTimezoneOffset())*z;var x=(t=new Date)=>{let e=(t.getDay()+6)%7,n=new Date(t);n.setDate(t.getDate()-e+3);let a=new Date(n.getFullYear(),0,1);return a.getDay()!==4&&a.setMonth(0,1+(11-a.getDay())%7),1+Math.floor((n-a+V(a,n))/B)};var Z=["` SUN` ` MON` ` TUE` ` WED` ` THU` ` FRI` ` SAT`","` MON` ` TUE` ` WED` ` THU` ` FRI` ` SAT` ` SUN`"],E=Number((0,o.getPreferenceValues)().weekStart),v=(0,o.getPreferenceValues)().showWeeks,S=new Date(new Date().getFullYear(),new Date().getMonth(),1);function P(){let[t,e]=(0,l.useState)(""),[n,a]=(0,l.useState)(""),[r,c]=(0,l.useState)(S);(0,l.useEffect)(()=>{(async()=>{let h=new C.Calendar(E).monthDates(r.getFullYear(),r.getMonth()),D="";h.forEach(b=>{if(v){let g=x(b[0]).toString();D+="`"+g+" ".repeat(2-g.length)+"`    "}b.forEach(g=>{let m=g.getMonth()===r.getMonth()?g.getDate().toString():"";g.toDateString()===new Date().toDateString()?D+="`\u2022"+" ".repeat(3-m.length)+m+"` ":D+="`"+" ".repeat(4-m.length)+m+"` "}),D+=`

`});let M=r.toLocaleString("en",{month:"long",year:"numeric"}),F=v?"`# `    ":"";a(M),e("# "+M+`
***
`+F+Z[E]+`

`+D)})()},[r]);let i=f=>{let h=new Date(r.getFullYear(),r.getMonth()+f,1);c(h)},u=f=>{let h=new Date(r.getFullYear()+f,r.getMonth(),1);c(h)},s=()=>{r===S?(0,o.showToast)(o.ToastStyle.Success,"Current month is on screen"):c(S)};return _jsx(o.Detail,{markdown:t,actions:_jsx(o.ActionPanel,null,_jsx(o.ActionPanel.Section,{title:n},_jsx(o.ActionPanel.Item,{title:"Current Month",shortcut:{modifiers:[],key:"c"},icon:{source:{dark:"up-dark.png",light:"up.png"}},onAction:()=>s()}),_jsx(o.CopyToClipboardAction,{content:t})),_jsx(o.ActionPanel.Section,{title:"Change Month"},_jsx(o.ActionPanel.Item,{title:"Previous Month",shortcut:{modifiers:[],key:"arrowLeft"},icon:{source:{dark:"left-dark.png",light:"left.png"}},onAction:()=>i(-1)}),_jsx(o.ActionPanel.Item,{title:"Next Month",shortcut:{modifiers:[],key:"arrowRight"},icon:{source:{dark:"right-dark.png",light:"right.png"}},onAction:()=>i(1)})),_jsx(o.ActionPanel.Section,{title:"Change Year"},_jsx(o.ActionPanel.Item,{title:"Previous Year",shortcut:{modifiers:["shift"],key:"arrowLeft"},icon:{source:{dark:"double-left-dark.png",light:"double-left.png"}},onAction:()=>u(-1)}),_jsx(o.ActionPanel.Item,{title:"Next Year",shortcut:{modifiers:["shift"],key:"arrowRight"},icon:{source:{dark:"double-right-dark.png",light:"double-right.png"}},onAction:()=>u(1)})))})}module.exports=j(G);0&&(module.exports={});
/*!
 * calendar.js: inspired by the calendar module from Python
 * Copyright(c) 2011 Luciano Ramalho <luciano@ramalho.org>
 * MIT Licensed
 */
/*!
 * weeknumber
 * @author commenthol
 * @license Unlicense
 */
