#!/bin/sh
# shellcheck disable=SC1091

#
# Pre hooks
#

# Intialize Homebrew
if [ -f /opt/homebrew/bin/brew ]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

#
# Locale
#

export LC_ALL="${LC_ALL:-en_US.UTF-8}"

#
# Browser
#

if [ "$(uname -s)" = "Darwin" ]; then
  export BROWSER="open"
elif [ "$(uname -s)" = "Linux" ]; then
  export BROWSER="xdg-open"
else
  export BROWSER="start"
fi

#
# Editors
#

export EDITOR="${EDITOR:-micro}"
export VISUAL="code --wait"
export PAGER="less --mouse"
export LESS="-g -i -M -R -S -w -z-4"

#
# Paths
#

export PATH="$HOME/.local/bin:$PATH"

export PATH="$HOMEBREW_PREFIX/bin:$PATH"
export PATH="$HOMEBREW_PREFIX/sbin:$PATH"
export PATH="$HOMEBREW_PREFIX/opt/curl/bin:$PATH"
export PATH="$HOMEBREW_PREFIX/opt/libressl/bin:$PATH"
export PATH="$HOMEBREW_PREFIX/opt/ruby/bin:$PATH"
export PATH="$HOMEBREW_PREFIX/opt/swift/bin:$PATH"
export PATH="$HOMEBREW_PREFIX/opt/zip/bin:$PATH"
export PATH="$HOMEBREW_PREFIX/opt/unzip/bin:$PATH"

export ANDROID_HOME="$HOMEBREW_PREFIX/share/android-commandlinetools"
export ANDROID_SDK_ROOT="$ANDROID_HOME"
export ANDROID_AVD_HOME="$HOME/.android/avd"
export PATH="$ANDROID_SDK_ROOT/platform-tools:$PATH"
export PATH="$ANDROID_SDK_ROOT/emulator:$PATH"
export PATH="$ANDROID_SDK_ROOT/tools:$PATH"

export DOCKER_HOME="$HOME/.docker"
export PATH="$DOCKER_HOME/bin:$PATH"

export GOPATH="$HOME/.go"
export PATH="$GOPATH/bin:$PATH"

export MODULAR_HOME="$HOME/.modular"
export PATH="$HOME/.modular/pkg/packages.modular.com_mojo/bin:$PATH"

export CARGOPATH="$HOME/.cargo"
export PATH="$CARGOPATH/bin:$PATH"

export PUB_CACHE="$HOME/.pub-cache"
export PATH="$PUB_CACHE/bin:$PATH"

export FVM_CACHE_PATH="$HOME/.fvm"
export PATH="$FVM_CACHE_PATH/default/bin:$PATH"

export PATH="$HOME/.jenv/bin:$PATH"

export PATH="$HOME/.bun/bin:$PATH"

#
# Miscellaneous
#

export CHROME_EXECUTABLE="/Applications/Chromium.app/Contents/MacOS/Chromium"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export PYTHON="/opt/homebrew/bin/python3"
export NI_DEFAULT_AGENT="bun"
export NI_GLOBAL_AGENT="bun"

#
# Aliases
#

# alias z="zi"
# alias c="clear"
alias cat="bat"
alias vim="nvim"
alias nano="micro"
alias npx="bun x"
alias pnpx="bun x"
alias python="python3"
alias syncer='$HOME/.script/syncer.sh'
alias lsa="eza --all --long --icons --tree --level 1 --no-permissions --no-user --time-style long-iso --git --sort=name --group-directories-first --binary"
