#!/bin/sh

#
# Pre hooks
#

# Homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

# Auto start tmux
if command -v tmux >/dev/null 2>&1 && [ -n "$PS1" ] && [ -z "$TMUX" ] && [ -z "$EMACS" ] && [ -z "$VIM" ] && [ "$VSCODE_RESOLVING_ENVIRONMENT" != "1" ]; then
  if [ "$TERM_PROGRAM" = "iTerm.app" ]; then
    session_name=$(printf '%s:%s' "$TTY" "$PWD" | md5sum | cut -c 1-6)
    (tmux set-option -g destroy-unattached off && tmux attach -t "$session_name" || tmux new -s "$session_name") 1>/dev/null 2>&1 && exit
  else
    session_name="$(date +%s | md5sum | cut -c 1-6)"
    (tmux new -d -s "$session_name" \; set destroy-unattached on \; attach -t "$session_name") 1>/dev/null 2>&1 && exit
  fi
fi

#
# Browser
#

if [ "$(uname -s)" = "Darwin" ]; then
  export BROWSER="open"
elif [ "$(uname -s)" = "Linux" ]; then
  export BROWSER="xdg-open"
else
  export BROWSER="start"
fi

#
# Editors
#

export EDITOR='micro'
export VISUAL='code --wait'
export PAGER='less --mouse'
export LESS='-g -i -M -R -S -w -z-4'

#
# Paths
#

[ -f "$HOME/.shellpath" ] && . "$HOME/.shellpath"
