complete -c atuin -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c atuin -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_use_subcommand" -f -a "history" -d 'manipulate shell history'
complete -c atuin -n "__fish_use_subcommand" -f -a "import" -d 'import shell history from file'
complete -c atuin -n "__fish_use_subcommand" -f -a "server" -d 'start an atuin server'
complete -c atuin -n "__fish_use_subcommand" -f -a "stats" -d 'calculate statistics for your history'
complete -c atuin -n "__fish_use_subcommand" -f -a "init" -d 'output shell setup'
complete -c atuin -n "__fish_use_subcommand" -f -a "uuid" -d 'generates a UUID'
complete -c atuin -n "__fish_use_subcommand" -f -a "search" -d 'interactive history search'
complete -c atuin -n "__fish_use_subcommand" -f -a "sync" -d 'sync with the configured server'
complete -c atuin -n "__fish_use_subcommand" -f -a "login" -d 'login to the configured server'
complete -c atuin -n "__fish_use_subcommand" -f -a "logout" -d 'log out'
complete -c atuin -n "__fish_use_subcommand" -f -a "register" -d 'register with the configured server'
complete -c atuin -n "__fish_use_subcommand" -f -a "key" -d 'print the encryption key for transfer to another machine'
complete -c atuin -n "__fish_use_subcommand" -f -a "gen-completions" -d 'generate shell completions'
complete -c atuin -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c atuin -n "__fish_seen_subcommand_from history" -s h -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from history" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from history" -f -a "start" -d 'begins a new command in the history'
complete -c atuin -n "__fish_seen_subcommand_from history" -f -a "end" -d 'finishes a new command in the history (adds time, exit code)'
complete -c atuin -n "__fish_seen_subcommand_from history" -f -a "list" -d 'list all items in history'
complete -c atuin -n "__fish_seen_subcommand_from history" -f -a "last" -d 'get the last command ran'
complete -c atuin -n "__fish_seen_subcommand_from history" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c atuin -n "__fish_seen_subcommand_from start" -s h -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from start" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from end" -s e -l exit
complete -c atuin -n "__fish_seen_subcommand_from end" -s h -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from end" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from list" -s c -l cwd
complete -c atuin -n "__fish_seen_subcommand_from list" -s s -l session
complete -c atuin -n "__fish_seen_subcommand_from list" -s h -l human
complete -c atuin -n "__fish_seen_subcommand_from list" -l cmd-only -d 'Show only the text of the command'
complete -c atuin -n "__fish_seen_subcommand_from list" -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from list" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from last" -s h -l human
complete -c atuin -n "__fish_seen_subcommand_from last" -l cmd-only -d 'Show only the text of the command'
complete -c atuin -n "__fish_seen_subcommand_from last" -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from last" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from import" -s h -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from import" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from import" -f -a "auto" -d 'import history for the current shell'
complete -c atuin -n "__fish_seen_subcommand_from import" -f -a "zsh" -d 'import history from the zsh history file'
complete -c atuin -n "__fish_seen_subcommand_from import" -f -a "bash" -d 'import history from the bash history file'
complete -c atuin -n "__fish_seen_subcommand_from import" -f -a "resh" -d 'import history from the resh history file'
complete -c atuin -n "__fish_seen_subcommand_from import" -f -a "fish" -d 'import history from the fish history file'
complete -c atuin -n "__fish_seen_subcommand_from import" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c atuin -n "__fish_seen_subcommand_from auto" -s h -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from auto" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from zsh" -s h -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from zsh" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from bash" -s h -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from bash" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from resh" -s h -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from resh" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from fish" -s h -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from fish" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from server" -s h -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from server" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from server" -f -a "start" -d 'starts the server'
complete -c atuin -n "__fish_seen_subcommand_from server" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c atuin -n "__fish_seen_subcommand_from start" -s h -l host -d 'specify the host address to bind'
complete -c atuin -n "__fish_seen_subcommand_from start" -s p -l port -d 'specify the port to bind'
complete -c atuin -n "__fish_seen_subcommand_from start" -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from start" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from stats" -s h -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from stats" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from stats" -f -a "all" -d 'compute statistics for all of time'
complete -c atuin -n "__fish_seen_subcommand_from stats" -f -a "day" -d 'compute statistics for a single day'
complete -c atuin -n "__fish_seen_subcommand_from stats" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c atuin -n "__fish_seen_subcommand_from all" -s h -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from all" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from day" -s h -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from day" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from init" -s h -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from init" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from init" -f -a "zsh" -d 'zsh setup'
complete -c atuin -n "__fish_seen_subcommand_from init" -f -a "bash" -d 'bash setup'
complete -c atuin -n "__fish_seen_subcommand_from init" -f -a "fish" -d 'fish setup'
complete -c atuin -n "__fish_seen_subcommand_from init" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c atuin -n "__fish_seen_subcommand_from zsh" -s h -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from zsh" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from bash" -s h -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from bash" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from fish" -s h -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from fish" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from uuid" -s h -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from uuid" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from search" -s c -l cwd -d 'filter search result by directory'
complete -c atuin -n "__fish_seen_subcommand_from search" -l exclude-cwd -d 'exclude directory from results'
complete -c atuin -n "__fish_seen_subcommand_from search" -s e -l exit -d 'filter search result by exit code'
complete -c atuin -n "__fish_seen_subcommand_from search" -l exclude-exit -d 'exclude results with this exit code'
complete -c atuin -n "__fish_seen_subcommand_from search" -s b -l before -d 'only include results added before this date'
complete -c atuin -n "__fish_seen_subcommand_from search" -l after -d 'only include results after this date'
complete -c atuin -n "__fish_seen_subcommand_from search" -s i -l interactive -d 'open interactive search UI'
complete -c atuin -n "__fish_seen_subcommand_from search" -s h -l human -d 'use human-readable formatting for time'
complete -c atuin -n "__fish_seen_subcommand_from search" -l cmd-only -d 'Show only the text of the command'
complete -c atuin -n "__fish_seen_subcommand_from search" -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from search" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from sync" -s f -l force -d 'force re-download everything'
complete -c atuin -n "__fish_seen_subcommand_from sync" -s h -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from sync" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from login" -s u -l username
complete -c atuin -n "__fish_seen_subcommand_from login" -s p -l password
complete -c atuin -n "__fish_seen_subcommand_from login" -s k -l key -d 'the encryption key for your account'
complete -c atuin -n "__fish_seen_subcommand_from login" -s h -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from login" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from logout" -s h -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from logout" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from register" -s u -l username
complete -c atuin -n "__fish_seen_subcommand_from register" -s e -l email
complete -c atuin -n "__fish_seen_subcommand_from register" -s p -l password
complete -c atuin -n "__fish_seen_subcommand_from register" -s h -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from register" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from key" -s h -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from key" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from gen-completions" -s s -l shell -d 'set the shell for generating completions'
complete -c atuin -n "__fish_seen_subcommand_from gen-completions" -s o -l out-dir -d 'set the output directory'
complete -c atuin -n "__fish_seen_subcommand_from gen-completions" -s h -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from gen-completions" -s V -l version -d 'Prints version information'
complete -c atuin -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c atuin -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
