# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

[plugins.pre]
inline = """
"""

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-autocomplete]
github = "marlonrichert/zsh-autocomplete"
hooks.pre = """
zstyle '*:compinit' arguments -i -u -w
zstyle ':autocomplete:*' delay 0.1
zstyle ':autocomplete:*' widget-style menu-select
"""

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
hooks.pre = """
export ZSH_AUTOSUGGEST_STRATEGY=(history completion)
export ZSH_AUTOSUGGEST_USE_ASYNC=1
export ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
"""

[plugins.zsh-edit]
github = "marlonrichert/zsh-edit"

[plugins.ohmyzsh]
github = "ohmyzsh/ohmyzsh"
use = [
  "lib/correction.zsh",
  "plugins/gnu-utils/gnu-utils.plugin.zsh",
  "plugins/dircycle/dircycle.plugin.zsh",
  "plugins/zoxide/zoxide.plugin.zsh",
  "plugins/brew/brew.plugin.zsh",
  "plugins/vscode/vscode.plugin.zsh",
  "plugins/xcode/xcode.plugin.zsh",
  "plugins/starship/starship.plugin.zsh",
]
hooks.pre = """
export ENABLE_CORRECTION=true
export SPROMPT="zsh: correct %F{1}%R%f to %F{2}%r%f [nyae]? "
export STARSHIP_CONFIG="$HOME/.config/starship/config.toml"
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_UNINSTALL_DEPENDENCIES=1
export HOMEBREW_NO_ENV_HINTS=1
"""
hooks.post = """
unsetopt correct_all
setopt correct
"""

[plugins.fzf-zsh-plugin]
github = "unixorn/fzf-zsh-plugin"

[plugins.zsh-node-bin]
github = "remcohaszing/zsh-node-bin"

[plugins.post]
inline = """
export ATUIN_NOBIND="true"
source <(atuin init zsh)
bindkey '^[[A' _atuin_search_widget
bindkey '^[OA' _atuin_search_widget

bindkey '\t' menu-select
bindkey -M menuselect '\t' menu-complete
bindkey -M menuselect '\r' .accept-line
bindkey '\t' autosuggest-accept

source <(carapace _carapace zsh)

eval "$(jenv init -)"

eval "$(pay-respects zsh --alias)"
"""
