forwarder https://apple.dns.nextdns.io/34ffa7/Yusoof%E2%80%99s%20Mac/Apple%20~macbook-air#45.90.28.0,2a07:a8c0::,45.90.30.0,2a07:a8c1::
cache-size 100MB
cache-max-age 0s
max-ttl 4s
discovery-dns 
timeout 2s
debug false
log-queries false
detect-captive-portals false
use-hosts true
listen 127.0.0.1:53
profile 
report-client-info false
bogus-priv true
max-inflight-requests 512
setup-router false
auto-activate true
control /var/run/nextdns.sock
hardened-privacy false
mdns disabled
